name: Update README

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'src/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Generate README from project info
      run: python generate_readme.py

    - name: Commit and Push README Changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "GitHub Actions"
        author_email: "actions@github.com"
        message: "Update README file"
